[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn", "openssl"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = [
  "yarn workspace api prisma:generate",
  "yarn workspace api build",
  "yarn workspace web build"
]

[start]
cmd = "yarn workspace api start"

